---
# ------------------------------------------------------------------------
# Telekom Security - Compliance Automation - Hardening
# Linux OS for Servers (3.65)
# Tasks: 05 MAC
# ------------------------------------------------------------------------

# Req 52:	If a system has Internet facing services or is a virtualization host,
# a MAC solution must be used.

- name: req-043.0 install mandatory access control solution
  package:
    name: '{{ use_mac_package }}'
    state: present
  when: config_mac == true

# Req 53:	If SELinux is used, it must not be disabled in bootloader configuration.

- name: req-044.1 enable selinux in grub
  lineinfile:
    dest: '/etc/default/grub'
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT=(.*)'
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet"'
  notify: update grub
  when: ( config_mac == true and config_mac_grub == true ) and
        ( use_mac_type == "selinux" and config_bootloader_grub == true )

- name: req-044.2 enable selinux in grub
  lineinfile:
    dest: '/etc/default/grub'
    regexp: '^GRUB_CMDLINE_LINUX=(.*)'
    line: 'GRUB_CMDLINE_LINUX=""'
  notify: update grub
  when: ( config_mac == true and config_mac_grub == true ) and
        ( use_mac_type == "selinux" and config_bootloader_grub == true )

# Req 54:	If SELinux is used, its state must be enforced.

- name: req-045.0 enforce selinux state
  lineinfile:
    dest: '/etc/selinux/config'
    regexp: '^SELINUX=(.*)'
    line: 'SELINUX=enforcing'
  when: config_mac == true and
        ( config_sel_enforced == true and use_mac_type == "selinux" )

# Req 55:	If SELinux is used, the policy must be configured.

- name: req-046.0 configure selinux policy
  lineinfile:
    dest: '/etc/selinux/config'
    regexp: '^SELINUXTYPE=(.*)'
    line: 'SELINUXTYPE={{ use_selinux_type }}'
  when: config_mac == true and
        ( config_sel_policy == true and use_mac_type == "selinux" )

# Req 56:	If SELinux is used, SETroubleshoot and MCS Translation Service must
# not be installed.

- name: req-047.0 deinstall not needed selinux tools are installed
  package:
    name: '{{ item }}'
    state: absent
  with_items: "{{ disable_sel_tools }}"
  when: config_mac == true and
        ( config_disable_sel_tools == true and ansible_os_family == "RedHat" )

# Req 57:	If SELinux is used, events must be logged if configuration of SELinux
# is modified.

# -w /etc/selinux/ -p wa -k MAC-policy
# -w /usr/share/selinux/ -p wa -k MAC-policy

# Req 58:	If AppArmor is used, it must not be disabled in bootloader configuration.

- name: req-044.1 enable apparmor in grub
  lineinfile:
    dest: '/etc/default/grub'
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT=(.*)'
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet"'
  notify: update grub
  when: ( config_mac == true and config_mac_grub == true ) and
        ( use_mac_type == "apparmor" and config_bootloader_grub == true )

- name: req-044.2 enable apparmor in grub
  lineinfile:
    dest: '/etc/default/grub'
    regexp: '^GRUB_CMDLINE_LINUX=(.*)'
    line: 'GRUB_CMDLINE_LINUX=""'
  notify: update grub
  when: ( config_mac == true and config_mac_grub == true ) and
        ( use_mac_type == "apparmor" and config_bootloader_grub == true )

# Req 59:	AppArmor is used, its state must be enforced.

- name: req-048.1 install apparmor-utils to enforce profiles
  package:
    name: 'apparmor-utils'
    state: present
  when: config_mac == true and
       ( use_mac_type == "apparmor" == config_aa_enforced == true)

- name: req-048.2 enforce apparmor profiles
  shell: aa-enforce /etc/apparmor.d/usr* >/dev/null 2>&1
  changed_when: false
  when: config_mac == true and
       ( use_mac_type == "apparmor" == config_aa_enforced == true)

# Req 60:	If AppArmor is used, events must be logged if configuration of AppArmor
# is modified.

# -w /etc/apparmor/ -p wa -k MAC-policy
# -w /etc/apparmor.d/ -p wa -k MAC-policy
