---

# Req 1: Unused services and protocols must be deactivated.


# Req 2: The reachability of services must be restricted.


# Req 3: Unused software must not be installed or must be uninstalled.
