---
# ------------------------------------------------------------------------
# Telekom Security - Compliance Automation
# Linux OS for Servers (3.65)
# Tasks
# ------------------------------------------------------------------------

# Stop playbook if Linux distro and version is not supported.
- fail:
    msg: "Your {{ansible_distribution}} version {{ ansible_distribution_version }} is not supported!"
  when: (ansible_distribution != "Ubuntu" and ansible_os_family != "RedHat" and ansible_os_family != "Amazon") or
        (ansible_distribution == "CentOS" and ansible_distribution_major_version != "7") or
        (ansible_distribution == "RedHat" and ansible_distribution_major_version != "7") or
        (ansible_distribution == "Ubuntu" and ansible_distribution_version != "14.04") and
        (ansible_distribution == "Ubuntu" and ansible_distribution_version != "16.04") and
        (ansible_distribution == "Ubuntu" and ansible_distribution_version != "18.04")

# Read variables for detected OS from '/vars/<linux-os>.yml' files
- name: read variables for detected os
  include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "{{ ansible_os_family }}.yml"
      - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
      - "{{ ansible_distribution }}.yml"
      skip: true

# System update (as requested with Req 19) must be done before security
# configuration. That's why relevante tasks are placed here!

- name: req-019.1 upgrade linux os (ubuntu)
  apt:
    upgrade: dist
    update_cache: yes
    cache_valid_time: 3600
    force_apt_get: no
  when: ansible_os_family == "Debian" and
      ( do_system_upgrade and not ansible_check_mode)

- name: req-019.2 upgrade linux os (redhat)
  yum:
    name: '*'
    state: latest
  when: ansible_os_family == "RedHat" and
      ( do_system_upgrade and not ansible_check_mode)

#- import_tasks: test.yml

- name: 01 basic hardening
  include_vars: linux(01)basic-hardening.yml
  import_tasks: linux(01)basic-hardening.yml

#- import_tasks: test.yml

  tags: basic_hardening

#- name: 02 logging
#  include_vars: linux(02)logging.yml
#  import_tasks: linux(02)logging.yml
#  tags: logging

#- name: 03 logging
#  include_vars: inux(03)pam.yml
#  import_tasks: linux(03)pam.yml
#  tags: pam

#- name: 04 iptables
#  include_vars: linux(04)iptables.yml
#  import_tasks: linux(04)iptables.yml
#  tags: iptables

#- name: 05 mac
#  include_vars: linux(05)mac.yml
#  import_tasks: linux(05)mac.yml
#  tags: mac

#- name: 06 compliance checks
#  include_vars: linux(06)compliance_checks.yml
#  import_tasks: linux(06)compliance_checks.yml
#  tags: compliance_checks
