---

- debug:
    msg: OS Family "{{ ansible_os_family }}"
- debug:
    msg: Distro "{{ ansible_distribution }}"
- debug:
    msg: Distro Version "{{ ansible_distribution_version }}"
- debug:
    msg: Distro Major Version "{{ ansible_distribution_major_version }}"

- block:
    - name: req-005.1 check partitions
      lineinfile:
        path: '/etc/fstab'
        line: "{{item}} "
        state: present
      register: check_partitions
      failed_when: check_partitions.changed
      with_items:
        - "{{ partitions }}"
  rescue:
    - debug:
        msg: "Req-005 (1/1): FAILED"
  when: config_partitions and ansible_check_mode
