---

- debug:
    msg: OS Family "{{ ansible_os_family }}"
- debug:
    msg: Distro "{{ ansible_distribution }}"
- debug:
    msg: Distro Version "{{ ansible_distribution_version }}"
- debug:
    msg: Distro Major Version "{{ ansible_distribution_major_version }}"
- debug:
    msg: Architecture "{{ ansible_architecture }}"

# ---------------------------------------------------------------------

- name: req-045.1 uninstall outdated pam-cracklib
  package:
    name: '{{ os_pam_cracklib }}'
    state: absent
  when: config_pam_password_rules

- name: req-045.2 install 'libpam-pwquality'
  package:
    name: 'libpam-pwquality'
    state: present
  when: config_pam_password_rules and ansible_distribution == "Ubuntu"

- name: req-045.3 configure password pwquality for pam
  pamd:
    name: "{{ item }}"
    type: password
    control: requisite
    module_path: pam_pwquality.so
    module_arguments:
      - retry=3
    state: args_present
  with_items: "{{ os_pamd_config_files }}"
  when: config_pam_password_rules
