---

- debug:
    msg: OS Family "{{ ansible_os_family }}"
- debug:
    msg: Distro "{{ ansible_distribution }}"
- debug:
    msg: Distro Version "{{ ansible_distribution_version }}"
- debug:
    msg: Distro Major Version "{{ ansible_distribution_major_version }}"

- block:
    - name: req-003.1 uninstall servers
      package:
        name: '{{ item }}'
        state: absent
      with_items: '{{ list_uninstall_servers }}'
      register: check_servers
      failed_when: check_servers.changed and ansible_check_mode
  rescue:
      - debug:
          msg: "FAILED: req-003 (1/2)"
  when: uninstall_servers

- block:
    - name: req-003.2 uninstall clients
      package:
        name: '{{ item }}'
        state: absent
      with_items: '{{ list_uninstall_clients }}'
      register: check_clients
      failed_when: check_clients.changed and ansible_check_mode
  rescue:
    - debug:
        msg: "FAILED: req-003 (2/2)"
  when: uninstall_clients
