---
# ------------------------------------------------------------------------
# Telekom Security - Compliance Automation
# SSH (3.04)
# Tasks
# ------------------------------------------------------------------------

# Stop playbook if Linux distro and version is not supported.
- fail:
    msg: "Your {{ansible_distribution}} version {{ ansible_distribution_version }} is not supported!"
  when: (ansible_distribution != "Ubuntu" and ansible_os_family != "RedHat" and ansible_os_family != "Amazon") or
        (ansible_distribution == "CentOS" and ansible_distribution_major_version != "7") or
        (ansible_distribution == "RedHat" and ansible_distribution_major_version != "7") or
        (ansible_distribution == "Ubuntu" and ansible_distribution_version != "14.04") and
        (ansible_distribution == "Ubuntu" and ansible_distribution_version != "16.04") and
        (ansible_distribution == "Ubuntu" and ansible_distribution_version != "18.04")

# Read variables for detected OS from '/vars/<linux-os>.yml' files
- name: read variables for detected os
  include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "{{ ansible_os_family }}.yml"
      - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
      - "{{ ansible_distribution }}.yml"
      skip: true

- name: 01 ssh requirements
  include_vars: ssh(01)ssh-requirements.yml
  import_tasks: ssh(01)ssh-requirements.yml

#- import_tasks: test.yml

  tags: basic_hardening
